version: "3.7"

services:
  postgres:
    image: postgres:17
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  rocketstocks:
    image: ghcr.io/jwolf34/rocketstocks:latest
    restart: always
    env_file: .env
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - rocketstocks_data:/RocketStocks/data
      - rocketstocks_logs:/RocketStocks/logs

volumes:
  postgres_data:
  rocketstocks_data:
  rocketstocks_logs:
